tap 'caskroom/homebrew-cask' || true
tap 'universal-ctags/universal-ctags' || true
tap 'homebrew/cask-versions'
tap 'homebrew/bundle' || true
tap 'uptech/homebrew-oss' || true

brew install uptech/oss/alt

brew 'mas'

brew 'universal-ctags', args: ['HEAD']
brew 'bash'
brew 'bash-completion@2'
brew 'bat'
brew 'ctop'
brew 'curl-openssl'
brew 'fzf'
brew 'tmux'
brew 'coreutils'
brew 'less'
brew 'ncdu'
brew 'openssh'
brew 'p7zip'
brew 'the_silver_searcher'
brew 'tree'
brew 'wget'
brew 'ripgrep'
brew 'fd'
brew 'tldr'

brew 'docbook' # to compile the mutt info page
brew 'urlview'
brew 'offlineimap'

# Kubernetes
brew 'kubectl'
brew 'kubectx'
brew 'helm'
brew 'stern'

cask 'docker-edge'

brew 'git'
brew 'tig'

brew 'imagemagick'

brew 'node'
brew 'yarn'

brew 'tidy-html5'
brew 'poppler'
brew 'jq'

# Casks
cask '0xed'
cask '1password'
cask 'anki'
cask 'authy'
cask 'calibre'
cask 'carbon-copy-cloner'
cask 'coconutbattery'
cask 'dash'
cask 'deadbeef-devel'
cask 'dosbox-app'
cask 'dropbox'
cask 'firefox'
cask 'flux'
cask 'gimp'
cask 'google-chrome'
cask 'google-chrome-canary'
cask 'grandperspective'
cask 'imageoptim'
cask 'istat-menus'
cask 'iterm2'
cask 'kid3'
cask 'mactex'
cask 'nextcloud'
cask 'pgadmin4'
cask 'sequel-pro'
cask 'slack'
cask 'teamviewer'
cask 'vlc'
# cask 'vmware-fusion'

# Mas

mas 'Affinity Photo', id: 824183456
