# vi: syntax=sh
# See helpful info at
# http://superuser.com/questions/183870/difference-between-bashrc-and-bash-profile/183980#183980
if [ -r ~/.profile ]; then
  . ~/.profile;
fi

if [ -r ~/.bash_functions ]; then
  . ~/.bash_functions
fi

OS_SPECIFIC_BASH_PROFILE=~/dotfiles/os/dots/bash_profile
if [ -f $OS_SPECIFIC_BASH_PROFILE ]; then
	source $OS_SPECIFIC_BASH_PROFILE
fi

# Only read .bashrc when shell is interactive
case "$-" in *i*) if [ -r ~/.bashrc ]; then . ~/.bashrc; fi;; esac
