# From http://superuser.com/questions/183870/difference-between-bashrc-and-bash-profile/183980#183980 :
#
# ~/.bashrc is the place to put stuff that applies only to bash itself,
# such as alias and function definitions, shell options, and prompt settings.
# (You could also put key bindings there, but for bash they normally go into
#  ~/.inputrc.)

# Careful: bashrc might be sourced for non-interactive shells, in
# particular scp, see
# http://lists.gnu.org/archive/html/bug-bash/2012-06/msg00028.html
# scp breaks when it encounters output, so all echos etc. must be
# avoided, and explicitly only happen when in interactive mode

if [ -z "$PS1" ]; then
  return
fi

alias be="bundle exec"
alias k="kubectl"
alias kx="kubectx"
alias dc="docker-compose"
alias ti="vim ~/Documents/Dropbox/notes/todos/tickler.taskpaper"
if command -v xdg-open >/dev/null; then
  alias open="xdg-open"
fi

# Prompt initialization
if [ "$(id -u)" -eq 0 ]; then
  PROMPT_CHAR="#"
else
  PROMPT_CHAR="$"
fi

if command -v git >/dev/null 2>&1; then
  function gitprompt {
    BRANCH=$(git branch 2>/dev/null | cut -f2 -d* -s | cut -b 2-)
    if [ "$BRANCH" ]; then
      echo "[$BRANCH]"
    fi
    echo ""
  }
  export PS1='\u@\h:\w$(gitprompt)\n$(date +'%H:%M:%S') $PROMPT_CHAR '
else
  export PS1='\h:\w$(date +'%H:%M:%S') $PROMPT_CHAR '
fi

# See "I have [bash] history back to ~2003" on https://news.ycombinator.com/item?id=10162189
# (for a different take, see http://mywiki.wooledge.org/BashFAQ/088 )
# According to my initial test, and according to one tweet in the discussion, on OS X, it is necessary
# to create the directory first:
HISTDIR=${HOME}/.history/$(date -u +%Y/%m/)
if [ ! -d "$HISTDIR" ]; then
  mkdir -p "$HISTDIR"
fi
# When testing, remember that the history is only written on session *exit*
# (see http://stackoverflow.com/questions/19454837/bash-histsize-vs-histfilesize )
shopt -s histappend
HISTFILESIZE= # Never truncate the file
# Use ignoreboth instead of ignoredups so that tmux-resurrect history save
# commands will not be saved. See
# https://github.com/tmux-plugins/tmux-resurrect
HISTCONTROL=ignoreboth
HISTIGNORE='ls:bg:fg:history'
HOSTNAME="$(hostname)"
HOSTNAME_SHORT="${HOSTNAME%%.*}"
HISTFILE="${HOME}/.history/$(date -u +%Y/%m/%d.%H.%M.%S)_${HOSTNAME_SHORT}_$$"

# Use trap instead of PROMPT_COMMAND to append each command immediately instead
# of on session exit, minimizing the effect of sudden power losses
# See https://github.com/tmux-plugins/tmux-resurrect/issues/86
# PROMPT_COMMAND="history -a"
trap 'history -a $HISTFILE' DEBUG

OS_SPECIFIC_BASHRC=~/dotfiles/os/dots/bashrc
if [ -f $OS_SPECIFIC_BASHRC ]; then
  # shellcheck disable=SC1090
  source $OS_SPECIFIC_BASHRC
fi

HOST_SPECIFIC_BASHRC=~/dotfiles/local/dots/bashrc
if [ -f $HOST_SPECIFIC_BASHRC ]; then
  # shellcheck disable=SC1090
  source $HOST_SPECIFIC_BASHRC
fi

# shellcheck disable=SC1090
. "$HOME/dotfiles/bin/z.sh"

set -o vi

if [ -f ~/.fzf.bash ]; then
  # shellcheck source=/dev/null
  source ~/.fzf.bash
  # http://owen.cymru/fzf-ripgrep-navigate-with-bash-faster-than-ever-before/
  fzf1_='rg --files --no-ignore --hidden '
  fzf2_='--follow -g "!.ipynb_checkpoints" -g "!*.pyc" -g "!.mypy_cache" '
  fzf3_='-g "!{.git,node_modules,build,htmlcov,coverage,dist,venv}/*" '
  fzf4_='2> /dev/null'
  export FZF_DEFAULT_COMMAND=$fzf1_$fzf2_$fzf3_$fzf4_
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  # bind -x '"\C-p": vim $(fzf);'
fi
