# From http://superuser.com/questions/183870/difference-between-bashrc-and-bash-profile/183980#183980 :
#
# ~/.bashrc is the place to put stuff that applies only to bash itself,
# such as alias and function definitions, shell options, and prompt settings.
# (You could also put key bindings there, but for bash they normally go into
#  ~/.inputrc.)

# Careful: bashrc might be sourced for non-interactive shells, in
# particular scp, see
# http://lists.gnu.org/archive/html/bug-bash/2012-06/msg00028.html
# scp breaks when it encounters output, so all echos etc. must be
# avoided, and explicitly only happen when in interactive mode
if [ -z "$PS1" ]; then
  return
fi

alias t="todo.sh -td $HOME/dotfiles/bin/todo.cfg"
alias vt="vim $HOME/Documents/Dropbox/todo/todo.txt"
alias vo="vim $HOME/Documents/Dropbox/todo/outline.txt"
alias ct="clear;t"
alias tmux="TERM=screen-256color-bce tmux"
alias be="bundle exec"

# Prompt initialization
which git >/dev/null 2>&1
if [ $? -eq 0 ]; then
  function gitprompt {
    BRANCH=$(git branch 2>/dev/null | cut -f2 -d* -s | cut -b 2-)
    if [ "$BRANCH" ]; then
      echo "[$BRANCH]"
    fi
    echo ""
  }

  export PS1='\u@\h:\w$(gitprompt)
$ '
else
  export PS1='\h:\w $ '
fi

# See "I have [bash] history back to ~2003" on https://news.ycombinator.com/item?id=10162189
# (for a different take, see http://mywiki.wooledge.org/BashFAQ/088 )
# According to my initial test, and according to one tweet in the discussion, on OS X, it is necessary
# to create the directory first:
HISTDIR=${HOME}/.history/$(date -u +%Y/%m/)
if [ ! -d $HISTDIR ]; then
  mkdir -p $HISTDIR
fi
# When testing, remember that the history is only written on session *exit*
# (see http://stackoverflow.com/questions/19454837/bash-histsize-vs-histfilesize )
shopt -s histappend
# Append each command immediately, to minimize the effect of sudden power losses
# Otherwise, the history is only written on session exit
# http://apple.stackexchange.com/questions/114691/why-isnt-history-a-working
PROMPT_COMMAND="history -a"
HISTFILESIZE= # Never truncate the file
HOSTNAME="$(hostname)"
HOSTNAME_SHORT="${HOSTNAME%%.*}"
HISTFILE="${HOME}/.history/$(date -u +%Y/%m/%d.%H.%M.%S)_${HOSTNAME_SHORT}_$$"

OS_SPECIFIC_BASHRC=~/dotfiles/os/dots/bashrc
if [ -f $OS_SPECIFIC_BASHRC ]; then
  source $OS_SPECIFIC_BASHRC
fi

HOST_SPECIFIC_BASHRC=~/dotfiles/local/dots/bashrc
if [ -f $HOST_SPECIFIC_BASHRC ]; then
  source $HOST_SPECIFIC_BASHRC
fi

. $HOME/dotfiles/bin/z.sh

set -o vi
