# From http://superuser.com/questions/183870/difference-between-bashrc-and-bash-profile/183980#183980 :
#
# ~/.bashrc is the place to put stuff that applies only to bash itself,
# such as alias and function definitions, shell options, and prompt settings.
# (You could also put key bindings there, but for bash they normally go into
#  ~/.inputrc.)

# Careful: bashrc might be sourced for non-interactive shells, in
# particular scp, see
# http://lists.gnu.org/archive/html/bug-bash/2012-06/msg00028.html
# scp breaks when it encounters output, so all echos etc. must be
# avoided, and explicitly only happen when in interactive mode
if [ -z "$PS1" ]; then
  return
fi

alias tmux="TERM=screen-256color-bce tmux"
alias be="bundle exec"
alias dc="docker-compose"
alias ti="vim ~/Documents/Dropbox/notes/todos/tickler.taskpaper"
if command -v xdg-open >/dev/null; then
  alias open="xdg-open"
fi

# Prompt initialization
if [ "$(id -u)" -eq 0 ]; then
  PROMPT_CHAR="#"
else
  PROMPT_CHAR="$"
fi

if which git >/dev/null 2>&1; then
  function gitprompt {
    BRANCH=$(git branch 2>/dev/null | cut -f2 -d* -s | cut -b 2-)
    if [ "$BRANCH" ]; then
      echo "[$BRANCH]"
    fi
    echo ""
  }
  export PS1='\u@\h:\w$(gitprompt)\n$(date +'%H:%M:%S') $PROMPT_CHAR '
else
  export PS1='\h:\w$(date +'%H:%M:%S') $PROMPT_CHAR '
fi

# See "I have [bash] history back to ~2003" on https://news.ycombinator.com/item?id=10162189
# (for a different take, see http://mywiki.wooledge.org/BashFAQ/088 )
# According to my initial test, and according to one tweet in the discussion, on OS X, it is necessary
# to create the directory first:
HISTDIR=${HOME}/.history/$(date -u +%Y/%m/)
if [ ! -d "$HISTDIR" ]; then
  mkdir -p "$HISTDIR"
fi
# When testing, remember that the history is only written on session *exit*
# (see http://stackoverflow.com/questions/19454837/bash-histsize-vs-histfilesize )
shopt -s histappend
HISTFILESIZE= # Never truncate the file
# don't add duplicates and space-prefixed commands to the history:
HISTIGNORE=ignoreboth
HOSTNAME="$(hostname)"
HOSTNAME_SHORT="${HOSTNAME%%.*}"
HISTFILE="${HOME}/.history/$(date -u +%Y/%m/%d.%H.%M.%S)_${HOSTNAME_SHORT}_$$"

# Use trap instead of PROMPT_COMMAND to append each command immediately instead
# of on session exit, minimizing the effect of sudden power losses
# See https://github.com/tmux-plugins/tmux-resurrect/issues/86
# PROMPT_COMMAND="history -a"
trap 'history -a $HISTFILE' DEBUG
trap 'cat $HISTFILE >> $HOME/.bash_history' EXIT

OS_SPECIFIC_BASHRC=~/dotfiles/os/dots/bashrc
if [ -f $OS_SPECIFIC_BASHRC ]; then
  # shellcheck disable=SC1090
  source $OS_SPECIFIC_BASHRC
fi

HOST_SPECIFIC_BASHRC=~/dotfiles/local/dots/bashrc
if [ -f $HOST_SPECIFIC_BASHRC ]; then
  # shellcheck disable=SC1090
  source $HOST_SPECIFIC_BASHRC
fi

# shellcheck disable=SC1090
. "$HOME/dotfiles/bin/z.sh"

set -o vi

export NVM_DIR="/Users/andreas/.nvm"
# shellcheck disable=SC1090
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
# shellcheck disable=SC1090
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH="$HOME/.yarn/bin:$PATH"

if [ -f ~/.fzf.bash ]; then
  source ~/.fzf.bash
  # http://owen.cymru/fzf-ripgrep-navigate-with-bash-faster-than-ever-before/
  export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules,coverage,dist}/*" 2> /dev/null'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  # bind -x '"\C-p": vim $(fzf);'
fi
