" vi:expandtab ts=2 sw=2
set nocompatible
set modeline
filetype off

let mapleader = ","

source ~/.vim/bundles.vim

filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList          - list configured plugins
" :PluginInstall(!)    - install (update) plugins
" :PluginSearch(!) foo - search (or refresh cache first) for foo
" :PluginClean(!)      - confirm (or auto-approve) removal of unused plugins
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" -- General settings -----------------------------------------------------
set sessionoptions-=curdir
set sessionoptions+=sesdir

" Do not store global options. Otherwise the machine-specific runtimepath
" would also be stored, and Sessions would not be portable across different
" machines.
set sessionoptions-=options

let s:host_specific_pre_setup = expand("<sfile>").".host.pre.".hostname()
if findfile(s:host_specific_pre_setup,"<sfile>:%h") != ""
  source `=expand(s:host_specific_pre_setup)`
endif
unlet s:host_specific_pre_setup

if &term =~ "dtterm" 
  set t_Co=256
elseif &term =~ "xterm-256color"
  set t_Co=256
elseif  &term =~ "rxvt-unicode"
  set t_Co=88
"2010-04-03: The following two lines don't help on Linux - my term is
"xterm, and I have 256 colors there. Will have to adapt this to work on all
"machines; in the meantime just commenting it out.
"elseif &term =~ "xterm"
"  set t_Co=8
endif

if &term =~ "dtterm" || &term =~ "xterm"|| &term =~ "rxvt-unicode"
  if has("terminfo")
    set t_Sf=<Esc>[3%p1%dm
   set t_Sb=<Esc>[4%p1%dm
 else
   set t_Sf=<Esc>[3%dm
   set t_Sb=<Esc>[4%dm
 endif
endif

set nohlsearch
set visualbell
set autoindent
set incsearch
set sidescroll=1
" FIXME:exrc is not necessary if I am in $HOME/.vim
" Then, the whole configuration will be sourced twice.
set exrc " enable reading of local .vimrc and .exrc files
set winminheight=0 " minimize a window to just its status bar
set textwidth=75
set statusline=%<%f\ %h%m%r%{fugitive#statusline()}%=%-14.(%l,%c%V%)\ %P
set laststatus=2
set diffopt=filler,vertical

let g:netrw_alto = 1 " split below the file browser

au BufReadPost quickfix  set nowrap

if &t_Co > 2 || has("gui_running")
  syntax on
  highlight Statement ctermfg=1
endif
if &t_Co >= 256 || has("gui_running")
" 2010-04-03 Switched to a black desktop theme where a black colorscheme is
" needed, therefore using desert256 now.
" colorscheme default256
  colorscheme desert256
  " desert256's original comment color is darkcyan, which is too dark on a
  " black background. Changing to cyan:
  hi Comment       ctermfg=cyan
elseif &t_Co >= 88
  colorscheme desert256
"  colorscheme inkpot
  " desert256's original comment color is darkcyan, which is too dark on a
  " black background. Changing to cyan:
  hi Comment       ctermfg=cyan
endif
if has("gui_running")
  set guioptions-=m " remove menu bar
  set guioptions-=T " remove tool bar
endif

" Using "ctermbg=White" will only use gray background on an iTerm with 256
" colors, therefore using 255 instead.
highlight Visual term=reverse ctermbg=255 guibg=White

source <sfile>.handling_gzip
source <sfile>.tip343_large_files
source <sfile>.tip112_indentation_helper

" -- OS-specific settings -------------------------------------------------
let s:os = "unknown"
if has("mac")
  let s:os="mac"
elseif has("unix")
  let s:os="unix"
elseif has("win32")
  let s:os="win32"
" else nothing specific to be done.
endif
if s:os != "unknown"
  let s:os_specific_setup = expand("<sfile>").".os.".s:os
  if findfile(s:os_specific_setup,"<sfile>:%h") != ""
    source `=expand(s:os_specific_setup)`
  endif
  unlet s:os_specific_setup
endif
unlet s:os

" -- host-specific settings -----------------------------------------------
let s:host_specific_setup = expand("<sfile>").".host.".hostname()
if findfile(s:host_specific_setup,"<sfile>:%h") != ""
  source `=expand(s:host_specific_setup)`
endif
unlet s:host_specific_setup

" Vim Tip 173: Quick movement between split windows
nmap <c-l> <c-w>l
nmap <c-h> <c-w>h
nmap <c-k> <c-w>k
nmap <c-j> <c-w>j

" In the tskeleton plugin, g:tskelMapGoToNextTag is by default
" mapped to <c-j>, but that would override the setting above.
" Hence I define the variable differently here (in particular,
" that is, *before* the plugin is loaded).
let g:tskelMapGoToNextTag = '<c-n>'

" Overriding a few VCSCommands with fugitive equivalents
nmap \cs :Gstatus
nmap \cv :Gdiff
nmap \cl :Glog
nmap \cb :Gblame

let g:GetLatestVimScripts_allowautoinstall=1

if has("multi_byte")
	if &termencoding == ""
		let &termencoding = &encoding
	endif
	set encoding=utf-8                     " better default than latin1
	setglobal fileencoding=utf-8           " change default file encoding when writing new files
endif
set encoding=utf-8                     " better default than latin1
set fileencoding=utf-8                     " better default than latin1
setglobal fileencoding=utf-8           " change default file encoding when writing new files

au FileType html let b:loaded_delimitMate = 1
au FileType xml let b:loaded_delimitMate = 1

" For YouCompleteMe
let g:ycm_extra_conf_globlist = ['~/*']

" Helpful to get rid of the space when typing
" dabbreviations:
func! Eatchar(pat)
  let c = nr2char(getchar(0))
  return (c =~ a:pat) ? '' : c
endfunc

" Switching ; and : to increase editing speed and comfort.
" nnoremap ; :
" nnoremap : ;

" source ~/.vim/plist.vim
