#!/bin/sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --init

if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
    if ! command -v brew >/dev/null 2>&1; then
        echo "Installing homebrew"
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    # In Posix sh, echo flags are undefined
    if [ "$(echo -n)" = "-n" ]; then
        n=""
        # c="\c"
    else
        n="-n"
        # c=""
    fi

    echo $n "Install apps in Brewfile (y/n)? "
    read -r answer
    if [ "$answer" != "${answer#[Yy]}" ] ;then
        if [ -f "$HOME/.config/brewfile/Brewfile" ]; then
            echo "Installing complete bundle"
            brew bundle --file=~/.config/brewfile/Brewfile
        else
            echo "Installing minimal bundle"
            brew bundle --file=~/.config/brewfile/Brewfile.minimal
        fi
    fi

    tic $HOME/dotfiles/share/terminfo/screen-256color-italic.terminfo
    tic -xs $HOME/dotfiles/share/terminfo/tmux-256color.terminfo
    tic $HOME/dotfiles/share/terminfo/xterm-256color-italic.terminfo
fi

if command -v rbenv; then
    echo "rbenv detected. Installing rbenv-default-gems ..."
    git clone https://github.com/rbenv/rbenv-default-gems.git $(rbenv root)/plugins/rbenv-default-gems
fi


GPG_TTY=$(tty) yadm --yadm-archive "$HOME/.local/share/yadm/archive-repo/archive" decrypt
