require('autocommands.git')
require('autocommands.ruby')
require('autocommands.telescope')
require('autocommands.ruby_stacktrace')
vim.cmd([[autocmd FileType json,html,xml,yaml set tabstop=2 shiftwidth=2 expandtab]])
vim.cmd([[autocmd BufRead,BufNewFile * if getline(1) =~ '^\(From \|Return-path: \)' | set filetype=mail | endif]])
