if [ -f `brew --prefix`/share/bash-completion/bash_completion ]; then
	. `brew --prefix`/share/bash-completion/bash_completion
fi

alias ncdu="ncdu --color dark -rr -x --exclude .git --exclude node_modules"
