alias ncdu="ncdu --color dark -rr -x --exclude .git --exclude node_modules"
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"
# https://superuser.com/questions/31744/how-to-get-git-completion-bash-to-work-on-mac-os-x/482943#482943
if [ -f "$(brew --prefix)/etc/bash_completion.d/git-completion.bash" ]; then
. "$(brew --prefix)/etc/bash_completion.d/git-completion.bash"
fi
